# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new dev build to TestFlight"
  lane :dev do
    increment_build_number(xcodeproj: "telehealthapp.xcodeproj")
    build_app(
      workspace: "telehealthapp.xcworkspace", 
      scheme: "Dev",
      configuration: "Dev.Release",
    )
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end

  desc "Push a new test build to TestFlight"
  lane :test do
    increment_build_number(xcodeproj: "telehealthapp.xcodeproj")
    build_app(
      workspace: "telehealthapp.xcworkspace",
      scheme: "Test",
      configuration: "Test.Release",
    )
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end

  desc "Push a new prod build to TestFlight"
  lane :prod do
    increment_build_number(xcodeproj: "telehealthapp.xcodeproj")
    build_app(
      workspace: "telehealthapp.xcworkspace",
      scheme: "Prod",
      configuration: "Prod.Release",
    )
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end

  desc "Get certificates"
  lane :certificates do |options|
    match(
      type: "appstore",
      app_identifier: ["app.telehealth.dev, app.telehealth.test, app.telehealth"],
      username:"praveen.jayarajan@gmail.com",
      readonly: true,
      clone_branch_directly: true,
      git_url: "https://github.com/pjay79/telehealthapp-certificates"
    )
  end
  
  desc "Install appstore and development certificates for local development"
  lane :devcertificates do |options|
    match(
      type: "appstore",
      app_identifier: ["app.telehealth.dev, app.telehealth.test, app.telehealth"],
      username:"praveen.jayarajan@gmail.com",
      readonly: false,
      git_url: "https://github.com/pjay79/telehealthapp-certificates"
    )
    match(
      type: "development",
      app_identifier: ["app.telehealth.dev, app.telehealth.test, app.telehealth"],
      username:"praveen.jayarajan@gmail.com",
      readonly: false,
      git_url: "https://github.com/pjay79/telehealthapp-certificates"
    )
  end
end
