# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new dev build to TestFlight"
  lane :dev do
    increment_build_number
    build_app(
      workspace: "telehealthapp.xcworkspace", 
      scheme: "Dev",
      configuration: "Release",
      clean: true,
      export_options: {
        method: "app-store",
        provisioningProfiles: { 
          "app.reactnative.telehealthdev" => "match AppStore app.reactnative.telehealthdev",
        },
      }
    )
    upload_to_testflight(
      username: "praveen.jayarajan@gmail.com",
      team_id: '119188381',
      skip_waiting_for_build_processing: true
    )
  end

  desc "Push a new test build to TestFlight"
  lane :test do
    increment_build_number
    build_app(
      workspace: "telehealthapp.xcworkspace",
      scheme: "Test",
      configuration: "Test.Release",
      clean: true,
      export_options: {
        method: "app-store",
        provisioningProfiles: { 
          "app.reactnative.telehealthtest" => "match AppStore app.reactnative.telehealthtest",
        },
      }
    )
    upload_to_testflight(
      username: "praveen.jayarajan@gmail.com",
      team_id: '119188381',
      skip_waiting_for_build_processing: true
    )
  end

  desc "Push a new prod build to TestFlight"
  lane :prod do
    increment_build_number
    build_app(
      workspace: "telehealthapp.xcworkspace",
      scheme: "Prod",
      configuration: "Prod.Release",
      clean: true,
      export_options: {
        method: "app-store",
        provisioningProfiles: { 
          "app.reactnative.telehealth" => "match AppStore app.reactnative.telehealth",
        },
      }
    )
    upload_to_testflight(
      username: "praveen.jayarajan@gmail.com",
      team_id: '119188381',
      skip_waiting_for_build_processing: true
    )
  end

  desc "Get certificates"
  lane :certificates do
    match(
      type: "appstore",
      app_identifier: ["app.reactnative.telehealthdev, app.reactnative.telehealthtest, app.reactnative.telehealth"],
      username:"praveen.jayarajan@gmail.com",
      readonly: true,
      git_url: "https://github.com/pjay79/telehealthapp-certificates"
    )
  end
  
  desc "Install appstore and development certificates for local development"
  lane :devcertificates do
    match(
      type: "appstore",
      app_identifier: ["app.reactnative.telehealthdev, app.reactnative.telehealthtest, app.reactnative.telehealth"],
      username:"praveen.jayarajan@gmail.com",
      readonly: false,
      git_url: "https://github.com/pjay79/telehealthapp-certificates"
    )
    match(
      type: "development",
      app_identifier: ["app.telehealth.dev, app.telehealth.test, app.telehealth"],
      username:"praveen.jayarajan@gmail.com",
      readonly: false,
      git_url: "https://github.com/pjay79/telehealthapp-certificates"
    )
  end
end
