# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  lane :bump_version_code do
    path = '../app/build.gradle'
    re = /versionCode\s+(\d+)/ 
  
    s = File.read(path)
    versionCode = s[re, 1].to_i
    s[re, 1] = (versionCode + 1).to_s
  
    f = File.new(path, 'w')
    f.write(s)
    f.close
  end

  desc "Deploy a new Dev version to Google Play"
  lane :dev do
    gradle(task: "clean")
    bump_version_code
    gradle(
      task: "bundleDevRelease",
      flags: "--no-daemon"
    )
    upload_to_play_store(
      release_status: "draft",
      track: "alpha"
    )
  end

  desc "Deploy a new QA version to Google Play"
  lane :dev do
    gradle(task: "clean")
    bump_version_code
    gradle(
      task: "bundleQaRelease",
      flags: "--no-daemon"
    )
    upload_to_play_store(
      release_status: "draft",
      track: "alpha"
    )
  end

  desc "Deploy a new Prod version to Google Play"
  lane :dev do
    gradle(task: "clean")
    bump_version_code
    gradle(
      task: "bundleProdRelease",
      flags: "--no-daemon"
    )
    upload_to_play_store(
      release_status: "draft",
      track: "alpha"
    )
  end
end
